CREATE TABLE HOTEL(
	HOTELID INTEGER,
	STREET VARCHAR(20) NOT NULL,
	COUNTRY VARCHAR(15) NOT NULL,
	STATE VARCHAR(15) NOT NULL,
	ZIP INTEGER NOT NULL,
	CONSTRAINT PK_HOTEL
	PRIMARY KEY (HOTELID)
);

CREATE TABLE CUSTOMER(
	CID INTEGER,
	PHONENO VARCHAR(15) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	CONSTRAINT PK_CUSTOMER
	PRIMARY KEY (CID)
);

CREATE TABLE HOTEL_PHONE(
	HOTELID INTEGER,
	PHONENO VARCHAR(15),
	CONSTRAINT PK_HOTEL_PHONE
	PRIMARY KEY (HOTELID,PHONENO),
	CONSTRAINT FK_HOTEL_PHONE_HOTELID
	FOREIGN KEY (HOTELID) REFERENCES HOTEL(HOTELID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ROOM(
	HOTELID INTEGER,
	RNUMBER INTEGER,
	PRICE DECIMAL(10,2) NOT NULL,
	FLOORNO INTEGER NOT NULL,
	DESCRIPTION VARCHAR(50),
	CAPACITY INTEGER NOT NULL,
	RTYPE VARCHAR(10) NOT NULL,
	CONSTRAINT PK_ROOM
	PRIMARY KEY(HOTELID,RNUMBER),
	CONSTRAINT FK_ROOM_HOTELID
	FOREIGN KEY (HOTELID) REFERENCES HOTEL(HOTELID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OFFERROOM(
	HOTELID INTEGER,
	RNUMBER INTEGER,
	SDATE DATE NOT NULL UNIQUE,
	EDATE DATE NOT NULL,
	DISCOUNT DECIMAL(4,2) NOT NULL,
	CONSTRAINT PK_OFFERROOM
	PRIMARY KEY(HOTELID,RNUMBER),
	CONSTRAINT FK_OFFERROOM_HOTELID_RNUMBER
	FOREIGN KEY (HOTELID,RNUMBER) REFERENCES ROOM(HOTELID,RNUMBER)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RREVIEW(
	RID INTEGER,
	CID INTEGER NOT NULL,
	RATING INTEGER NOT NULL,
	TEXT VARCHAR(50),
	HOTELID INTEGER NOT NULL,
	RNUMBER INTEGER NOT NULL,
	CONSTRAINT PK_RREVIEW
	PRIMARY KEY(RID),
	CONSTRAINT FK_RREVIEW_HOTELID_RNUMBER
	FOREIGN KEY (HOTELID,RNUMBER) REFERENCES ROOM(HOTELID,RNUMBER)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_RREVIEW_CID
	FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BREAKFAST(
	HOTELID INTEGER,
	BTYPE VARCHAR(10),
	DESCRIPTION VARCHAR(50),
	PRICE DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_BREAKFAST
	PRIMARY KEY(HOTELID,BTYPE),
	CONSTRAINT FK_BREAKFAST_HOTELID
	FOREIGN KEY (HOTELID) REFERENCES HOTEL(HOTELID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BREVIEW(
	RID INTEGER,
	CID INTEGER NOT NULL,
	RATING INTEGER NOT NULL,
	TEXT VARCHAR(50),
	HOTELID INTEGER NOT NULL,
	BTYPE VARCHAR(10) NOT NULL,
	CONSTRAINT PK_BREVIEW
	PRIMARY KEY(RID),
	CONSTRAINT FK_BREVIEW_HOTELID_BTYPE
	FOREIGN KEY (HOTELID,BTYPE) REFERENCES BREAKFAST(HOTELID,BTYPE)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_BREVIEW_CID
	FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SERVICE(
	HOTELID INTEGER,
	STYPE VARCHAR(10),
	PRICE DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_SERVICE
	PRIMARY KEY(HOTELID,STYPE),
	CONSTRAINT FK_SERVICE_HOTELID
	FOREIGN KEY (HOTELID) REFERENCES HOTEL(HOTELID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SREVIEW(
	RID INTEGER,
	CID INTEGER NOT NULL,
	RATING INTEGER NOT NULL,
	TEXT VARCHAR(50),
	HOTELID INTEGER NOT NULL,
	STYPE VARCHAR(10) NOT NULL,
	CONSTRAINT PK_SREVIEW
	PRIMARY KEY(RID),
	CONSTRAINT FK_SREVIEW_HOTELID_STYPE
	FOREIGN KEY (HOTELID,STYPE) REFERENCES SERVICE(HOTELID,STYPE)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_SREVIEW_CID
	FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CREDITCARD(
	CNUMBER INTEGER,
	BADDRESS VARCHAR(100) NOT NULL,
	CTYPE VARCHAR(15) NOT NULL,
	CODE INTEGER NOT NULL,
	EXPDATE DATE NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CREDITCARD
	PRIMARY KEY (CNUMBER)
);

CREATE TABLE RESERVATION(
	INVOICENUMBER INTEGER,
	RDATE DATE NOT NULL,
	CONSTRAINT PK_RESERVATION
	PRIMARY KEY(INVOICENUMBER)
);

CREATE TABLE RESERVES(
	CID INTEGER NOT NULL,
	CNUMBER INTEGER NOT NULL,
	INVOICENUMBER INTEGER,
	CONSTRAINT PK_RESERVES
	PRIMARY KEY(INVOICENUMBER),
	CONSTRAINT FK_RESERVES_INVOICENO
	FOREIGN KEY (INVOICENUMBER) REFERENCES RESERVATION(INVOICENUMBER)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_RESERVES_CNUMBER
	FOREIGN KEY (CNUMBER) REFERENCES CREDITCARD(CNUMBER)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_RESERVES_CID
	FOREIGN KEY (CID) REFERENCES CUSTOMER(CID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ROOM_RES(
	INVOICENUMBER INTEGER NOT NULL,
	INDATE DATE,
	HOTELID INTEGER,
	RNUMBER INTEGER,
	OUTDATE DATE,
	CONSTRAINT PK_ROOMRES
	PRIMARY KEY(INDATE,HOTELID,RNUMBER),
	CONSTRAINT FK_ROOMRES_INVOICENO
	FOREIGN KEY (INVOICENUMBER) REFERENCES RESERVATION(INVOICENUMBER)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_ROOMRES_HOTELID_RNUMBER
	FOREIGN KEY (HOTELID,RNUMBER) REFERENCES ROOM(HOTELID,RNUMBER)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RES_ORDER(
	INDATE DATE,
	HOTELID INTEGER,
	RNUMBER INTEGER,
	BTYPE VARCHAR(10),
	NO_OF_ORDER INTEGER,
	CONSTRAINT PK_RESORDER
	PRIMARY KEY(INDATE,HOTELID,RNUMBER,BTYPE),
	CONSTRAINT FK_RESORDER_HOTELID_BTYPE
	FOREIGN KEY (HOTELID,BTYPE) REFERENCES BREAKFAST(HOTELID,BTYPE)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_RESORDER_HOTELID_RNUMBER_INDATE
	FOREIGN KEY (HOTELID,RNUMBER,INDATE) REFERENCES ROOM_RES(HOTELID,RNUMBER,INDATE)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RES_SERVICE(
	INDATE DATE,
	HOTELID INTEGER,
	RNUMBER INTEGER,
	STYPE VARCHAR(10),
	CONSTRAINT PK_RESSERVICE
	PRIMARY KEY(INDATE,HOTELID,RNUMBER,STYPE),
	CONSTRAINT FK_RESSERVICE_HOTELID_STYPE
	FOREIGN KEY (HOTELID,STYPE) REFERENCES SERVICE(HOTELID,STYPE)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_RESSERVICE_HOTELID_RNUMBER_INDATE
	FOREIGN KEY (HOTELID,RNUMBER,INDATE) REFERENCES ROOM_RES(HOTELID,RNUMBER,INDATE)
	ON DELETE CASCADE ON UPDATE CASCADE
);