# Generated by Django 3.1.3 on 2020-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='NA', max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='friendly_name',
            field=models.CharField(default='NA', max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='NA', max_length=40),
        ),
    ]
