# Generated by Django 3.1.3 on 2020-11-10 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cc_number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('r_date', models.DateField()),
                ('cc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.creditcard')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
