# Generated by Django 3.1.3 on 2020-11-10 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cc_number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('r_date', models.DateField()),
                ('cc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.creditcard')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
