# Generated by Django 3.1.3 on 2020-11-27 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='cid',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='reservations.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='hotel_id',
            field=models.ForeignKey(db_column='hotel_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.hotel'),
        ),
        migrations.AddField(
            model_name='roomreview',
            name='cid',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomreview',
            name='room_id',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.room'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='hotel_id',
            field=models.ForeignKey(db_column='hotel_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.hotel'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='invoice_number',
            field=models.ForeignKey(db_column='invoice_number', on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='room_no',
            field=models.ForeignKey(db_column='room_no', on_delete=django.db.models.deletion.CASCADE, to='reservations.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(db_column='hotel_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.hotel'),
        ),
        migrations.AddField(
            model_name='reservationservice',
            name='rr_id',
            field=models.ForeignKey(db_column='rr_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservationservice',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='reservations.service'),
        ),
        migrations.AddField(
            model_name='reservationbreakfast',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='reservations.breakfast'),
        ),
        migrations.AddField(
            model_name='reservationbreakfast',
            name='rr_id',
            field=models.ForeignKey(db_column='rr_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cc_number',
            field=models.ForeignKey(db_column='cc_number', on_delete=django.db.models.deletion.CASCADE, to='reservations.creditcard'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cid',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountedroom',
            name='room_id',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.room'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.UniqueConstraint(fields=('cc_number',), name='unique creditcard'),
        ),
        migrations.AddField(
            model_name='breakfastreview',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='reservations.breakfast'),
        ),
        migrations.AddField(
            model_name='breakfastreview',
            name='cid',
            field=models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='hotel_id',
            field=models.ForeignKey(db_column='hotel_id', on_delete=django.db.models.deletion.CASCADE, to='reservations.hotel'),
        ),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.UniqueConstraint(fields=('cid', 'sid'), name='unique servicereview'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('hotel_id', 's_type'), name='unique hotelservicetype'),
        ),
        migrations.AddConstraint(
            model_name='roomreview',
            constraint=models.UniqueConstraint(fields=('cid', 'room_id'), name='unique roomreview'),
        ),
        migrations.AddConstraint(
            model_name='roomreservation',
            constraint=models.UniqueConstraint(fields=('invoice_number', 'hotel_id', 'room_no', 'check_in_date'), name='unique roomreservation'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel_id', 'room_no'), name='unique hotelroomid'),
        ),
        migrations.AddConstraint(
            model_name='reservationservice',
            constraint=models.UniqueConstraint(fields=('sid', 'rr_id'), name='unique roomresservice'),
        ),
        migrations.AddConstraint(
            model_name='reservationbreakfast',
            constraint=models.UniqueConstraint(fields=('bid', 'rr_id'), name='unique roomresbreakfast'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('cc_number', 'r_date'), name='unique reservation'),
        ),
        migrations.AddConstraint(
            model_name='breakfastreview',
            constraint=models.UniqueConstraint(fields=('cid', 'bid'), name='unique breakfastreview'),
        ),
        migrations.AddConstraint(
            model_name='breakfast',
            constraint=models.UniqueConstraint(fields=('hotel_id', 'b_type'), name='unique hotelbreakfasttype'),
        ),
    ]
